Repository mundipagg/amora-data-build-tool, pull requests merged in 2022-05, with the labels that each got.

#83 Adiciona shed como ferramenta de lint
  .github/workflows/pull-request.yaml
  .pre-commit-config.yaml
  amora/cli.py
  amora/config.py
  amora/contracts.py
  amora/feature_store/__init__.py
  amora/feature_store/decorators.py
  amora/feature_store/feature_view.py
  amora/feature_store/protocols.py
  amora/feature_store/registry.py
  amora/feature_store/type_mapping.py
  amora/materialization.py
  amora/models.py
  amora/protocols.py
  amora/providers/bigquery.py
  amora/storage.py
  amora/tests/assertions.py
  amora/tests/audit.py
  amora/tests/generic_tests.py
  amora/tests/pytest_plugin.py
  amora/transformations.py
  amora/utils.py
  examples/amora_project/models/health.py
  examples/amora_project/models/heart_agg.py
  examples/amora_project/models/heart_rate.py
  examples/amora_project/models/heart_rate_over_100.py
  examples/amora_project/models/step_count_by_source.py
  examples/amora_project/models/steps.py
  examples/amora_project/models/steps_agg.py
  examples/amora_project/tests/test_health.py
  examples/amora_project/tests/test_heart_agg.py
  examples/amora_project/tests/test_heart_rate.py
  examples/amora_project/tests/test_models_schema.py
  examples/amora_project/tests/test_steps.py
  poetry.lock
  pyproject.toml
  tests/cli/feature_store/test_feature_store_apply.py
  tests/cli/feature_store/test_feature_store_materialize.py
  tests/cli/test_compile.py
  tests/cli/test_materialize.py
  tests/cli/test_models_import.py
  tests/feature_store/test_decorators.py
  tests/feature_store/test_registry.py
  tests/models/heart_agg.py
  tests/models/heart_rate.py
  tests/models/heart_rate_over_100.py
  tests/models/step_count_by_source.py
  tests/models/steps.py
  tests/providers/test_bigquery.py
  tests/test_assertions.py
  tests/test_compilation.py
  tests/test_materialization.py
  tests/test_models.py
  tests/test_transformations.py
Labels: enhancement, dependencies, python

#95 Expões métricas para Prometheus
  amora/cli.py
  poetry.lock
  pyproject.toml
Labels: dependencies

#118 Fixes a bug that would cause an Amora Model view not to be materialized if a table already exists
  amora/materialization.py
  tests/test_materialization.py
Labels: bug
